/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.smartcity2.smartcityprojectfinal;

import generated.grpc.airquality.AirQuality;
import generated.grpc.airquality.AirQualityServiceGrpc;
import generated.grpc.airquality.Zone;
import generated.grpc.budget.BudgetAllocationServiceGrpc;
import generated.grpc.budget.BudgetPlan;
import generated.grpc.budget.BudgetPriorityRequest;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;
import smartcity.generated.neighborhood.NeighborhoodList;
import smartcity.generated.neighborhood.NeighborhoodRequest;
import smartcity.generated.neighborhood.NeighborhoodServiceGrpc;

/**
 *
 * @author ThomasNCI
 */
public class SmartCityGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SmartCityGUI.class.getName());
    //Neighborhood
    private NeighborhoodServiceGrpc.NeighborhoodServiceBlockingStub blockingStub;
    private StreamObserver<NeighborhoodRequest> requestObserver;
    private NeighborhoodServiceGrpc.NeighborhoodServiceStub asyncStub;
    //AirQuality
    private AirQualityServiceGrpc.AirQualityServiceStub airAsyncStub;
    //Budget
    // Budget
    private BudgetAllocationServiceGrpc.BudgetAllocationServiceStub budgetAsyncStub;
    private StreamObserver<BudgetPriorityRequest> budgetRequestObserver;

    /**
     * Creates new form SmartCityGUI
     */
    public SmartCityGUI() {
        initComponents();
        
        new Thread(() -> {
            try {
                // ServiceDiscovery using jmdns
                ServiceDiscovery sd1 = new ServiceDiscovery("_grpc._tcp.local.", "NeighborhoodService");
                int Np = sd1.discoverService(5000);

                ServiceDiscovery sd2 = new ServiceDiscovery("_grpc._tcp.local.", "AirQualityService");
                int Ap = sd2.discoverService(5000);

                ServiceDiscovery sd3 = new ServiceDiscovery("_grpc._tcp.local.", "BudgetService");
                int Bp = sd3.discoverService(5000);

                // IF JMDNS doesnt find use fixed ports as fallback
                if (Np == -1) {
                    Np = 50051;
                }
                if (Ap == -1) {
                    Ap = 50052;
                }
                if (Bp == -1) {
                    Bp = 50053;
                }
                
                final int neighborhoodPort = Np;
                final int airPort = Ap;
                final int budgetPort = Bp;

                ManagedChannel channel = ManagedChannelBuilder
                        .forAddress("localhost", neighborhoodPort)
                        .usePlaintext()
                        .build();

                ManagedChannel channel2 = ManagedChannelBuilder
                        .forAddress("localhost", airPort)
                        .usePlaintext()
                        .build();

                ManagedChannel channel3 = ManagedChannelBuilder
                        .forAddress("localhost", budgetPort)
                        .usePlaintext()
                        .build();

                blockingStub = NeighborhoodServiceGrpc.newBlockingStub(channel);
                asyncStub = NeighborhoodServiceGrpc.newStub(channel);
                airAsyncStub = AirQualityServiceGrpc.newStub(channel2);
                budgetAsyncStub = BudgetAllocationServiceGrpc.newStub(channel3);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        neighborhoodIdField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        CompleteButton = new javax.swing.JButton();
        AirQualityCheck = new javax.swing.JLabel();
        ZoneID = new javax.swing.JTextField();
        StartMonitoring = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result2Area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        StartBudget = new javax.swing.JButton();
        SendBudget = new javax.swing.JButton();
        Budget = new javax.swing.JButton();
        InsertID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Result3Area = new javax.swing.JTextArea();
        PriorityField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Neighborhood ID");

        neighborhoodIdField.setText("Insert ID");
        neighborhoodIdField.addActionListener(this::neighborhoodIdFieldActionPerformed);

        sendButton.setText("Send");
        sendButton.addActionListener(this::sendButtonActionPerformed);

        startButton.setText("Start");
        startButton.addActionListener(this::startButtonActionPerformed);

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        CompleteButton.setText("Complete");
        CompleteButton.addActionListener(this::CompleteButtonActionPerformed);

        AirQualityCheck.setText("Air Quality Check");

        ZoneID.setText("Zone");
        ZoneID.addActionListener(this::ZoneIDActionPerformed);
        ZoneID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ZoneIDKeyReleased(evt);
            }
        });

        StartMonitoring.setText("Start Monitoring");
        StartMonitoring.addActionListener(this::StartMonitoringActionPerformed);

        result2Area.setColumns(20);
        result2Area.setRows(5);
        jScrollPane2.setViewportView(result2Area);

        jLabel1.setText("Neighborhood Budgeting");

        StartBudget.setText("Start");
        StartBudget.addActionListener(this::StartBudgetActionPerformed);

        SendBudget.setText("Send");
        SendBudget.addActionListener(this::SendBudgetActionPerformed);

        Budget.setText("Budget");
        Budget.addActionListener(this::BudgetActionPerformed);

        InsertID.setText("Insert Neighborhood ID");

        Result3Area.setColumns(20);
        Result3Area.setRows(5);
        jScrollPane3.setViewportView(Result3Area);

        PriorityField.setText("Priority");
        PriorityField.addActionListener(this::PriorityFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InsertID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PriorityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(StartBudget)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SendBudget)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Budget))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AirQualityCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZoneID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StartMonitoring))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neighborhoodIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CompleteButton)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(neighborhoodIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton)
                    .addComponent(startButton)
                    .addComponent(CompleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirQualityCheck)
                    .addComponent(ZoneID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartMonitoring))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(InsertID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriorityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartBudget)
                            .addComponent(SendBudget)
                            .addComponent(Budget))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String id = neighborhoodIdField.getText().trim();

        if (requestObserver == null) {
            resultArea.setText("Click START first\n");
            return;
        }

        NeighborhoodRequest request
                = NeighborhoodRequest.newBuilder()
                        .setNeighborhoodId(id)
                        .build();

        requestObserver.onNext(request);

        resultArea.append("Sent: " + id + "\n");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        requestObserver = asyncStub.analyzeNeighborhoods(
                new StreamObserver<NeighborhoodList>() {

            @Override
            public void onNext(NeighborhoodList value) {
                resultArea.append("Final result:\n");
                value.getNeighborhoodsList().forEach(n
                        -> resultArea.append(n.toString() + "\n"));
            }

            @Override
            public void onError(Throwable t) {
                String msg = t.getMessage();

                if (msg != null && msg.contains("not found")) {
                    resultArea.append("Invalid neighborhood ID\n");
                } else {
                    resultArea.append("gRPC Error: " + msg + "\n");
                }
            }

            @Override
            public void onCompleted() {
                resultArea.append("Stream completed\n");
            }
        });

        resultArea.setText("Stream started...\n"); // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void neighborhoodIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neighborhoodIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neighborhoodIdFieldActionPerformed

    private void CompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteButtonActionPerformed
        if (requestObserver == null) {
            resultArea.setText("Click START first\n");
            return;
        }

        requestObserver.onCompleted();

        resultArea.append("Stream completed\n");
    }//GEN-LAST:event_CompleteButtonActionPerformed

    private void ZoneIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoneIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZoneIDActionPerformed

    private void StartMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartMonitoringActionPerformed

        String zone = ZoneID.getText().trim();

        if (zone.isEmpty()) {
            result2Area.setText("Enter zone\n");
            return;
        }

        result2Area.setText("Monitoring started...\n");

        Zone request = Zone.newBuilder()
                .setZone(zone)
                .build();

        airAsyncStub.monitorAirQuality(request,
                new StreamObserver<AirQuality>() {

            @Override
            public void onNext(AirQuality value) {
                result2Area.append(
                        "Zone: " + value.getZone()
                        + " | PM2.5: " + value.getPm25()
                        + " | CO2: " + value.getCo2()
                        + " | NO2: " + value.getNo2()
                        + " | Level: " + value.getLevel() + "\n"
                );
            }

            @Override
            public void onError(Throwable t) {
                String msg = t.getMessage();

                if (msg != null && msg.contains("Zone can't be empty")) {
                    result2Area.append("Invalid zone. Please enter a valid one.\n");
                } else {
                    result2Area.append("gRPC Error: " + msg + "\n");
                }
            }

            @Override
            public void onCompleted() {
                result2Area.append("Monitoring finished\n");
            }
        });

    }//GEN-LAST:event_StartMonitoringActionPerformed

    private void ZoneIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ZoneIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ZoneIDKeyReleased

    private void StartBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBudgetActionPerformed
        budgetRequestObserver = budgetAsyncStub.allocateBudget(
                new StreamObserver<BudgetPlan>() {

            @Override
            public void onNext(BudgetPlan value) {
                Result3Area.append(
                        "Neighborhood: " + value.getNeighborhoodId()
                        + " | Allocated: " + value.getAllocatedAmount()
                        + " | Status: " + value.getStatus() + "\n"
                );
            }

            @Override
            public void onError(Throwable t) {
                String msg = t.getMessage();

                if (msg != null && msg.contains("not found")) {
                    Result3Area.append("Neighborhood not found\n");
                } else {
                    Result3Area.append("gRPC Error: " + msg + "\n");
                }
            }

            @Override
            public void onCompleted() {
                Result3Area.append("Budgetting completed\n");
            }
        });

        Result3Area.setText("Budget stream started\n");
    }//GEN-LAST:event_StartBudgetActionPerformed

    private void SendBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBudgetActionPerformed
        if (budgetRequestObserver == null) {
            Result3Area.setText("Click START first\n");
            return;
        }

        String id = InsertID.getText().trim();
        int priority = Integer.parseInt(PriorityField.getText().trim());

        BudgetPriorityRequest request = BudgetPriorityRequest.newBuilder()
                .setNeighborhoodId(id)
                .setPriorityLevel(priority)
                .build();

        budgetRequestObserver.onNext(request);

        Result3Area.append("Sent: " + id + " (priority " + priority + ")\n");
    }//GEN-LAST:event_SendBudgetActionPerformed

    private void PriorityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriorityFieldActionPerformed

    private void BudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BudgetActionPerformed

        if (budgetRequestObserver == null) {
            Result3Area.setText("Click START first\n");
            return;
        }

        budgetRequestObserver.onCompleted();

        Result3Area.append("Client finished sending\n");

    }//GEN-LAST:event_BudgetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SmartCityGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirQualityCheck;
    private javax.swing.JButton Budget;
    private javax.swing.JButton CompleteButton;
    private javax.swing.JTextField InsertID;
    private javax.swing.JTextField PriorityField;
    private javax.swing.JTextArea Result3Area;
    private javax.swing.JButton SendBudget;
    private javax.swing.JButton StartBudget;
    private javax.swing.JButton StartMonitoring;
    private javax.swing.JTextField ZoneID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField neighborhoodIdField;
    private javax.swing.JTextArea result2Area;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
